### ISSUE TITLE
Price is returning value x100

### ISSUE THREAD

**Issue by vinarmani** [Bitcoin-com/bitbox-sdk#108]
The api being used for Price:

https://index-api.bitcoin.com/api/v0/cash/price/

is returning all values x100. Essentially, it is returning the price in cents rather than dollars.

**Comment by sterlingbeason** [comment]
> all values x100

Divide the values by 100. It seems the other modules don't deal in decimals, so I've just been doing that conversion.

**Comment by cgcardona** [comment]
Yes we're dividing by 100 in Badger: https://github.com/Bitcoin-com/badger/commit/25583a6722831cfebdda93b1845e33c926f20999#diff-2b5f4ebed417b2ca68a35f8d38cb3d64R116

In the past I had BITBOX SDK dividing by 100 but I thought that maybe some world currencies don't have 100 units so the math wouldn't work in those cases. So now we just return it in the same format as the price index you listed and divide by 100 in our apps.
