### ISSUE TITLE
Is mocha dependency necessary to run bitbox?

### ISSUE THREAD

**Issue by devalbo** [Bitcoin-com/bitbox-sdk#120]
I upgraded to bitbox-sdk 8.4.0 in my react/Typescript project and I think @types/mocha dependency is causing a conflict with my jest dependency. According to my package-lock.json, @types/mocha is needed by bitbox-sdk. Is this actually true? Or can you make it a dev dependency?

**Comment by cgcardona** [comment]
Thanks for pointing this out. I moved the types for `mocha`, `chai` and `sinon` to dev dependencies. The fix is in `bitbox-sdk` v8.4.2

🎩
