### ISSUE TITLE
BITBOX --scaffold didnt work out for me

### ISSUE THREAD

**Issue by theRealBitcoinClub** [Bitcoin-com/bitbox-sdk#27]
I tried to install BITBOX with scaffold, I tried Vue which would run fine in development mode: `npm run dev`

But then when i tried to build things i got errors:

1. `npm run build` wouldnt work as it says there is a build script missing
2. So i did some research and found out that I can run `node build\build.js`
3. I did then deploy that build to firebase but it gives me a blank screen: https://bitboxvue.firebaseapp.com/

[2018-10-09T18_58_44_337Z-debug.log](https://github.com/Bitcoin-com/bitbox-javascript-sdk/files/2461883/2018-10-09T18_58_44_337Z-debug.log)
[2018-10-09T18_58_49_782Z-debug.log](https://github.com/Bitcoin-com/bitbox-javascript-sdk/files/2461884/2018-10-09T18_58_49_782Z-debug.log)

I dont know why but the critical information is not included in the logs, so here that might help you:

> C:\Users\root\Documents\GitHub\vuefire\firetestagain>npm install --save bitbox-cli
> npm WARN deprecated babel-preset-es2015@6.24.1: ?  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to upda
> te!
> 
> > keccak@1.4.0 install C:\Users\root\Documents\GitHub\vuefire\firetestagain\node_modules\keccak
> > npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."
> 
> 
> > keccak@1.4.0 rebuild C:\Users\root\Documents\GitHub\vuefire\firetestagain\node_modules\keccak
> > node-gyp rebuild
> 
> 
> C:\Users\root\Documents\GitHub\vuefire\firetestagain\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Users\root\AppData\Roaming\npm\n
> ode_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\root\AppData\Roa
> ming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: C:\Users\root\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_in
> fo[:3];
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                                ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
> gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:336:11)
> gyp ERR! stack     at emitOne (events.js:116:13)
> gyp ERR! stack     at Socket.emit (events.js:211:7)
> gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:561:12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\root\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-g
> yp.js" "rebuild"
> gyp ERR! cwd C:\Users\root\Documents\GitHub\vuefire\firetestagain\node_modules\keccak
> gyp ERR! node -v v8.12.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the keccak@1.4.0 rebuild script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\root\AppData\Roaming\npm-cache\_logs\2018-10-09T18_58_44_337Z-debug.log
> "Keccak bindings compilation fail. Pure JS implementation will be used."
> 
> > secp256k1@3.5.2 install C:\Users\root\Documents\GitHub\vuefire\firetestagain\node_modules\secp256k1
> > npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."
> 
> 
> > secp256k1@3.5.2 rebuild C:\Users\root\Documents\GitHub\vuefire\firetestagain\node_modules\secp256k1
> > node-gyp rebuild
> 
> 
> C:\Users\root\Documents\GitHub\vuefire\firetestagain\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\root\AppData\Roaming\np
> m\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\root\AppData\
> Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: C:\Users\root\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_in
> fo[:3];
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                                ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
> gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:336:11)
> gyp ERR! stack     at emitOne (events.js:116:13)
> gyp ERR! stack     at Socket.emit (events.js:211:7)
> gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:561:12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\root\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-g
> yp.js" "rebuild"
> gyp ERR! cwd C:\Users\root\Documents\GitHub\vuefire\firetestagain\node_modules\secp256k1
> gyp ERR! node -v v8.12.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! secp256k1@3.5.2 rebuild: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the secp256k1@3.5.2 rebuild script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\root\AppData\Roaming\npm-cache\_logs\2018-10-09T18_58_49_782Z-debug.log
> "Secp256k1 bindings compilation fail. Pure JS implementation will be used."
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
> ch":"x64"})
> 
> + bitbox-cli@1.8.1
> added 342 packages from 628 contributors in 106.545s

I also tried to run 'npm run build' on the AngularScaffold which led to this error:

> C:\Users\root\Documents\GitHub\bitbox\TarifaCashAngular>npm run build
> 
> > bitbox@1.7.1 build C:\Users\root\Documents\GitHub\bitbox\TarifaCashAngular
> > ng build --prod
> 
> Date: 2018-10-09T18:38:16.519Z
> Hash: 057306fe7af8f27963f9
> Time: 16720ms
> chunk {0} styles.ac89bfdd6de82636b768.bundle.css (styles) 0 bytes [initial] [rendered]
> chunk {1} polyfills.997d8cc03812de50ae67.bundle.js (polyfills) 84 bytes [initial] [rendered]
> chunk {2} main.ee32620ecd1edff94184.bundle.js (main) 84 bytes [initial] [rendered]
> chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]
> 
> ERROR in src/app/app.component.ts(2,1): error TS1202: Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 'import
> * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bitbox@1.7.1 build: `ng build --prod`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the bitbox@1.7.1 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\root\AppData\Roaming\npm-cache\_logs\2018-10-09T18_38_16_673Z-debug.log
> 
> 

In the end I am able to use BITBOX without scaffold so things are fine for me, but I guess for a newbie that might lead to frustration and maybe you can fix that issue?

**Comment by cgcardona** [comment]
Thanks for bringing it to out attention. I'll check it out.

**Comment by cgcardona** [comment]
Closing due to not focusing on scaffolds atm. I've made a note in the vue readme pointing to this issue.
