### ISSUE TITLE
Discuss Crypto Library Usage

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/bitbox-sdk#33]
This issue is intended to foster discussion on different crypto libraries used. The pros and cons of working with each one.

Three popular crypto libraries are `scrypt`, `bcrypt`, and `bcryptjs`. bcrypt is a binary blob, compiled and included as a dependency. As a result, it breaks between versions of nodejs because it must be compiled for a specific version. bcryptjs is a javascript native, drop-in replacement for bcrypt. 

BITBOX apparently uses scrypt, and this message popped up in the [Discord chatroom](https://discord.gg/m5h28ND):

```
Got this error.The package at "node_modules/scryptsy/lib/scrypt.js" attempted to import the Node standard library module "crypto".It failed because React Native does not include the Node standard library.
```

**Comment by cgcardona** [comment]
We need to polyfill our Crypto class w/ crypto-browserify. I have it working for all the methods other than hash160

**Comment by cgcardona** [comment]
BITBOX's [Crypto Class](https://github.com/Bitcoin-com/bitbox-sdk/blob/master/lib/Crypto.ts) has been refactored to use Bitcoincashjs-lib's Crypto class so this isssue is no longer valid.
