### ISSUE TITLE
TransactionInput and AddressUtxoResult incompatible

### ISSUE THREAD

**Issue by istrau2** [Bitcoin-com/bitbox-sdk#37]
The docs show the following code:
```
const utxo = await this.bitbox.Address.utxo([sourceAddress]);
const rawTx = await this.wormhole.RawTransactions.create([utxo[0][0]], {});
```
however, with typescript it does not work because `TransactionInput` and `AddressUtxoResult` are different types. Probably `TransactionInput` should implement (or inherit from) `AddressUtxoResult`.

Regardless, how am I supposed to proceed here (i.e. how am I meant to be turning an `AddressUtxoResult` to `TransactionInput`. I can't even find a method to construct `TransactionInput` in the docs...

**Comment by cgcardona** [comment]
Closing as we no longer support Wormhole SDK
