### ISSUE TITLE
Price.current() giving inaccurate data

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/bitbox-sdk#50]
Reported by @paOol on the Discord channel:

paOolToday at 4:29 PM
i think the Price.current(); endpoint needs to be fixed;

https://media.discordapp.net/attachments/474254809076203520/524020375512809473/Screenshot_2018-12-16_16-29-30.png

if i specify .current('usd');
it shows the accurate price
https://developer.bitcoin.com/bitbox/docs/price

**Comment by cgcardona** [comment]
This should be resolved.
