### ISSUE TITLE
Expose `TransactionBuilder.setLockTime()`

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/bitbox-sdk#56]
`BITBOX.TransactionBuilder` needs to expose `setLockTime` which is part of `bitcoincashjs-lib`.

https://github.com/bigearth/bitcoincashjs-lib/blob/0a7fc7cf23551503f57689db4c930b8136db954c/src/transaction_builder.js#L488

**Comment by christroutner** [comment]
Discussion happened on the #bitbox-sdk discord channel: https://discord.gg/m5h28ND around 3:40PM PST 1/7/19

**Comment by cgcardona** [comment]
Handled here https://github.com/Bitcoin-com/bitbox-sdk/commit/b3f3fe210d4f3d3310db7092e0c466a4d389f62f
