### ISSUE TITLE
Add OP_RETURN example

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/bitbox-sdk#81]
Users have requested that we add a code examples to the `examples` directory that shows how to send out an OP_RETURN code that can be read via memo.cash.

**Comment by josephroyking** [comment]
Prelim starting point:

https://github.com/Bitcoin-com/bitbox-sdk/pull/82

Can expand to add more examples including constructing OP_RETURN transactions and formatting for memo.cash
