### ISSUE TITLE
bitbox.RawTransactions.sendRawTransaction fails with 414 error for large tx

### ISSUE THREAD

**Issue by blockparty-sh** [Bitcoin-com/bitbox-sdk#85]
This is because it was near 100kb tx. 

As a workaround, I can put the hex data in a single item array so that it uses POST. 

It seems to me though that there should only be a POST endpoint for this, GET implies idempotent whereas this is essentially inserting data / changing the state.

**Comment by christroutner** [comment]
Closing this, as this is essentially the same issue as #129, which is on the list of actionable tasks.
