### ISSUE TITLE
Update out-of-date type definitions

### ISSUE THREAD

**Issue by the-phoenix** [Bitcoin-com/bitbox-sdk#86]
Type definitions are not up-to-date. 
E.g: In HDNode type definition, there are `toCashAddress`, `toLegacyAddress` methods. 
But there's no implementation. Because it depends on 
https://github.com/Bitcoin-com/bitcoincashjs-lib/blob/master/src/hdnode.js which has no `toCashAddress` or `toLegacyAddress` definition.

**Comment by cgcardona** [comment]
BITBOX SDK has been ported completely to .ts. This should no longer be an issue.
